Removes Dependabot status badge
Spotifyd/spotifyd pull request #1080
Opened 2022-04-16 17:10 UTC by yadunandanbhat

As the original dependabot has stopped working, the badge link is broken. So this removes it. (See #1077 )

2022-04-16 21:14 UTC, eladyn requested changes
[This](https://github.com/Spotifyd/spotifyd/blob/ae6dac7a54f899316674ba57ce4a0f9890cd2b1c/README.md?plain=1#L41) line could be removed as well, otherwise LGTM.

2022-04-17 06:59 UTC, yadunandanbhat commented
Oh! i'll update it and push the commit

2022-04-17 07:04 UTC, yadunandanbhat commented
I've pushed the commit. Please review!

2022-04-17 12:04 UTC, eladyn approved these changes

2022-04-21 04:55 UTC, yadunandanbhat commented
I'm sorry for mentioning you for this small topic but @robinvd can you please review this so that it can be merged?

2022-04-21 22:36 UTC, robinvd approved these changes

2022-04-28 12:46 UTC, yadunandanbhat commented
can anyone else with write access review it?!

2022-09-06 16:45 UTC, merged

2022-09-06 16:45 UTC, SimonPersson commented
Thanks!