always emit the album art URL representing the largest image to DBus
Spotifyd/spotifyd pull request #1132
Opened 2022-10-28 08:01 UTC by l1na-forever

This patch ensures we always return the clearest possible album art URL as part of the MPRIS event sent over DBus. I noticed this after [mpris-notifier](https://github.com/l1na-forever/mpris-notifier) started showing blurry album art. Upon further inspection, the first album art item in the list returned by Spotify had become the smallest image's URL, rather than the largest.

Before:
![screenshot_20221028_005919254815550](https://user-images.githubusercontent.com/61861965/198535856-34ba6930-4eb5-4c76-b16f-6d204fc7c45a.png)

After:
![screenshot_20221028_005855845708237](https://user-images.githubusercontent.com/61861965/198535886-29a30d63-8d5a-4657-a56d-ce35e6b876f1.png)

2022-10-29 16:20 UTC, eladyn requested changes
Thank you very much for this. That is how it always should have been!

Only one question:

2022-10-29 16:20 UTC, eladyn commented on src/dbus_mpris.rs
> +                .max_by_key(|i| i.width.ok_or(0))
Shouldn't that be:

```suggestion
                .max_by_key(|i| i.width.unwrap_or(0))
```

2022-10-29 19:22 UTC, l1na-forever commented on src/dbus_mpris.rs
> +                .max_by_key(|i| i.width.ok_or(0))
Yup, it sound be :+1:

2022-10-30 12:24 UTC, eladyn approved these changes
Tested and working. Thank you!

2022-11-23 22:30 UTC, Plecra approved these changes
As it should be 😊 

Side note - It's a bit frustrating we can't test this, any ideas on how we could avoid regressions here (maybe spotify starts returning images with different levels of compression)?

2022-11-23 23:02 UTC, merged