Update the changelog for the 0.3.4 release
Spotifyd/spotifyd pull request #1141
Opened 2022-11-23 02:00 UTC by slondr

This just adds a line about the minimum rust version change which landed earlier today, and replaces the title of the "Unreleased" section with 0.3.4

2022-11-23 04:53 UTC, Plecra approved these changes
LGTM

2022-11-23 22:05 UTC, eladyn requested changes
Great to see the release coming together! Maybe we could get [this PR](https://github.com/Spotifyd/spotifyd/pull/1132) in before this one, since that is a small enough fix.

Most of the other PRs still need some work, so that is the only one I'd propose to merge before the release.

2022-12-14 18:50 UTC, NellyWhadsDev commented
Hey guys, is this release still on the radar? Could really use the config update for audio format as part of a formal release (I can install it manually, yes, but I use a rt kernel OS which only provides support for packages installed through their scripts)!

2022-12-15 02:13 UTC, slondr commented
Thanks for the bump, I lost track of eladyn's review 😅

2022-12-15 02:16 UTC, slondr commented on CHANGELOG.md
>  ### Added
I applied that patch to this branch - no need to complicate this further :)

2022-12-15 15:51 UTC, eladyn approved these changes
Thank you! 🎉

2022-12-15 16:00 UTC, merged