Add Windows Support
Spotifyd/spotifyd pull request #1219
Opened 2023-08-30 09:45 UTC by BKasin

Initial work by JCapucho in #602.

This PR rebases their work onto the latest commit in master. The `librespot` `--with-tremor` errors people were running into in some comments in the initial PR seem to be fixed. Config file handling should probably be updated, I'll look at it some tomorrow the next time I boot into Windows.

I built with: `cargo build --release --no-default-features --features rodio_backend`

2023-09-02 09:39 UTC, CrispyBaccoon commented
im currently getting these errors on Windows 11:
```rust
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:55:14
   |
55 | use std::os::unix::ffi::OsStringExt;
   |              ^^^^ could not find `unix` in `os`

error[E0433]: failed to resolve: could not find `unix` in `os`
  --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:56:14
   |
56 | use std::os::unix::io::AsRawFd;
   |              ^^^^ could not find `unix` in `os`

   Compiling hex v0.4.3
error[E0433]: failed to resolve: could not find `uid_t` in `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:396:74
    |
396 | ...e((pid, libc::uid_t::MAX - 1, gid)),
    |                  ^^^^^ could not find `uid_t` in `libc`

error[E0433]: failed to resolve: could not find `gid_t` in `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:397:79
    |
397 | ...d, uid, libc::gid_t::MAX - 1)),
    |                  ^^^^^ could not find `gid_t` in `libc`

error[E0412]: cannot find type `uid_t` in crate `libc`
  --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:67:14
   |
67 |     Id(libc::uid_t),
   |              ^^^^^ not found in `libc`

error[E0412]: cannot find type `uid_t` in crate `libc`
  --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:87:44
   |
87 |             inner: UserImpl::Id(t as libc::uid_t),
   |                                            ^^^^^ not found in `libc`

error[E0412]: cannot find type `gid_t` in crate `libc`
  --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:95:14
   |
95 |     Id(libc::gid_t),
   |              ^^^^^ not found in `libc`

error[E0412]: cannot find type `gid_t` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:115:45
    |
115 |             inner: GroupImpl::Id(t as libc::gid_t),
    |                                             ^^^^^ not found in `libc`

error[E0412]: cannot find type `mode_t` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:123:18
    |
123 |     inner: libc::mode_t,
    |                  ^^^^^^ not found in `libc`

error[E0412]: cannot find type `mode_t` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:129:35
    |
129 |             inner: inner as libc::mode_t,
    |                                   ^^^^^^ not found in `libc`

error[E0425]: cannot find function `umask` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:375:19
    |
375 |             libc::umask(self.umask.inner);
    |                   ^^^^^ not found in `libc`

error[E0412]: cannot find type `uid_t` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:393:50
    |
393 |                 let args: Option<(PathBuf, libc::uid_t, libc::gid_t)> =
    |                                                  ^^^^^ not found in `libc`

error[E0412]: cannot find type `gid_t` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:393:63
    |
393 |                 let args: Option<(PathBuf, libc::uid_t, libc::gid_t)> =
    |                                                               ^^^^^ not found in `libc`

error[E0412]: cannot find type `pid_t` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:434:49
    |
434 | unsafe fn perform_fork() -> Result<Option<libc::pid_t>, ErrorKind> {
    |                                                 ^^^^^ not found in `libc`

error[E0425]: cannot find function `fork` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:435:31
    |
435 |     let pid = check_err(libc::fork(), ErrorKind::Fork)?;
    |                               ^^^^ not found in `libc`

error[E0412]: cannot find type `pid_t` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:443:30
    |
443 | unsafe fn waitpid(pid: libc::pid_t) -> Result<libc::c_int, ErrorKind> {
    |                              ^^^^^ not found in `libc`

error[E0425]: cannot find function `waitpid` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:445:22
    |
445 |      check_err(libc::waitpid(pid, &mut child_ret, 0), ErrorKind::Wait)?;
    |                      ^^^^^^^ not found in `libc`

error[E0425]: cannot find function `setsid` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:450:21
    |
450 |     check_err(libc::setsid(), ErrorKind::DetachSession)?;
    |                     ^^^^^^ help: a function with a similar name exists: `getpid`
    |
   ::: C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\libc-0.2.140\src\windows\mod.rs:486:5
    |
486 |     pub fn getpid() -> ::c_int;
    |     -------------------------- similarly named function `getpid` defined here

error[E0425]: cannot find value `STDIN_FILENO` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:478:25
    |
478 |     process_stdio(libc::STDIN_FILENO, stdin)?;
    |                         ^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `STDOUT_FILENO` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:479:25
    |
479 |     process_stdio(libc::STDOUT_FILENO, stdout)?;
    |                         ^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `STDERR_FILENO` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:480:25
    |
480 |     process_stdio(libc::STDERR_FILENO, stderr)?;
    |                         ^^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `gid_t` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:487:51
    |
487 | unsafe fn get_group(group: Group) -> Result<libc::gid_t, ErrorKind> {
    |                                                   ^^^^^ not found in `libc`

error[E0412]: cannot find type `gid_t` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:500:34
    |
500 | unsafe fn set_group(group: libc::gid_t) -> Result<(), ErrorKind> {
    |                                  ^^^^^ not found in `libc`

error[E0425]: cannot find function `setgid` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:501:21
    |
501 |     check_err(libc::setgid(group), ErrorKind::SetGroup)?;
    |                     ^^^^^^ help: a function with a similar name exists: `getpid`
    |
   ::: C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\libc-0.2.140\src\windows\mod.rs:486:5
    |
486 |     pub fn getpid() -> ::c_int;
    |     -------------------------- similarly named function `getpid` defined here

error[E0412]: cannot find type `uid_t` in crate `libc`
   --> C:\Users\bowen\.cargo\registry\src\index.crates.io-6f17d22bba15001f\daemonize-0.5.0\src\lib.rs:505:48
    |
505 | unsafe fn get_user(user: User) -> Result<libc::uid_t, ErrorKind> {
    |                                                ^^^^^ not found in `l [...]

2023-09-02 09:46 UTC, BKasin commented
That is odd, daemonize shouldn't be getting pulled in at all when building on Windows. I've been testing on Windows 10, but can set up a Windows 11 VM on Monday to build in. For now, you can try doing `cargo clean` and then building again.

2023-09-06 21:33 UTC, BKasin commented
@CrispyBaccoon sorry it took a few extra days, my Windows 11 VM kept freezing every time I tried to use it so I had to make one on a different computer. I was able to get a successful build with `cargo build --release --no-default-features --features rodio_backend`. The only guess I have is that `daemonize` got added to the build deps cache before switching branches or something, so `cargo` was trying to build it because it was there.

2023-10-15 02:11 UTC, eladyn requested changes
Sorry for taking soo long to review this PR, I had a review sitting around for some time and forgot to finish it. :/

Thanks for the work anyway, other than the comments, this looks quite good to me.

2023-10-15 02:11 UTC, eladyn commented on src/config.rs
> +            Some(path)
I think, this could be replaced by `else if Path::new(&etc_conf).exists()`.

2023-10-15 03:24 UTC, BKasin commented on src/main.rs
> +            let mut log_file = dirs.config_dir().to_path_buf();
Windows logging is very unstandardized :/ It looks like preferred places are %LOCALAPPDATA%/program/program.log, or with the binary or config. I can change to LOCALAPPDATA.

2023-10-15 03:27 UTC, BKasin commented
No worries! I'll try and get to both comments tonight or tomorrow.

2023-10-15 07:45 UTC, BKasin commented
Pushing a rebase to resolve the merge conflict + moving the log file. Starting to fall asleep at my computer, so I'll come back to this in the afternoon.

2023-10-19 21:38 UTC, eladyn approved these changes
Thank you!

2023-10-19 21:39 UTC, merged

2026-07-14 20:31 UTC, God-damnit-all commented
So despite this PR, it seems Windows builds were never added to the Releases?

I could compile it manually of course, but that just seems like an odd omission.