Add support for `rodiojack` backend.
Spotifyd/spotifyd pull request #1281
Opened 2024-04-29 01:01 UTC by agdphd

The underlying `librespot` library already supports the JACK audio backend via `rodio`. Enabling it in `spotifyd` turns out to be dead simple--just needed to add the config enum elements to pass it through!

NOTE: I have tested this on my machine running Debian testing ("trixie"). The documentation for Fedora is based on the upstream docs for librespot: https://github.com/librespot-org/librespot/blob/329a1b16074af4d1a8abe2ed017b5d4a4a070ea1/COMPILING.md#audio-library-dependencies

2024-05-07 08:47 UTC, eladyn requested changes
Thank you for this PR! Only some small comments from my side.

2024-05-07 08:47 UTC, eladyn commented on src/config.rs
> +    feature = "jackaudio_backend",
I think, this might be a leftover from your testing? As this feature does not actually exist in the `Cargo.toml`.

2024-05-07 08:47 UTC, eladyn commented on src/config.rs
> +    "jackaudio",
Same here probably?

2024-05-07 09:44 UTC, eladyn commented
And I fixed the clippy lints in #1282, so if could rebase your changes, that would be nice as well

2024-06-01 18:00 UTC, agdphd commented
Thanks for your review! Removed the spurious `jackaudio` references and rebased to current `HEAD`.

2024-07-10 21:55 UTC, eladyn approved these changes
Thank you and sorry for taking so long for this simple PR!

2024-07-10 21:55 UTC, merged