Introduce use_mpris configuration setting
Spotifyd/spotifyd pull request #740
Opened 2020-12-21 18:35 UTC by valir

#730 

This defines the `use_mpris` configuration setting in the main
configuration file. Set this to `false` in case you have a headless
`spotifyd` instance, running in session lacking a dbus session.

2020-12-21 18:57 UTC, valir commented
Looks like the linter error is not in the code I've touched. Running the same `clippy` command on the master branch gives the same error.

2020-12-21 19:20 UTC, valir commented
Well, I've tried to come-up with this new feature and now I'm dragged down by errors with the linter on the code I don't touched and that are not reproducible on my laptop. Looks like the master code-base is not clean from the linter PoV. Please help me finish-up this pull request!

2020-12-23 20:30 UTC, robinvd commented
Hey @valir thanks so much for the PR on the issue i made! ill quickly check out the code and test it.

as for the CI other PRs also have this issue and i dont think it should be adressed here, when we fix it you can rebase/merge dev into this branch and the lint errors should go away. Sorry for the inconvience

2020-12-23 20:41 UTC, robinvd requested changes
code looks good, and quickly testing it seems to work great!

2020-12-23 20:41 UTC, robinvd commented on README.md
> +use_mpris = false
i think keeping the current behaviour might be best, so default to using dbus

2021-01-12 14:52 UTC, robinvd commented on README.md
> +use_mpris = false
Sorry i didnt explain it correctly, as it currenly is The Default impl of the settings (without a config) will set the value to false. And that would be a breaking change to existing users. I think the best solution would be to make it a `Option<bool>` then when setting the interal config do `config.shared_config.use_mpris.unwrap_or(true)`

2021-01-12 14:53 UTC, robinvd requested changes
the value should also be merged by the configs, at https://github.com/Spotifyd/spotifyd/pull/740/files#diff-cba64c21ab992eaad29fce147a08f4560a4769bc14682b8a96081a5fd02dbecdR517

2021-01-12 20:30 UTC, valir commented
After fetching upstream and rebasing on that master, I'm still getting `lint` errors in code I did not touched.

2021-01-12 21:03 UTC, robinvd commented
Yea that is unfortunately currently an issue. But we can just merge it even if there are lint errors

2021-01-12 21:08 UTC, robinvd commented on README.md
> +use_mpris = false
Looks great!

2021-01-12 21:39 UTC, valir commented
Looking forward for the merge as I'd like to see it landing on Archlinux Arm repos 😉

2021-01-12 23:14 UTC, robinvd commented
@valir maybe i missed it but did you adress this comment already? https://github.com/Spotifyd/spotifyd/pull/740#pullrequestreview-566350806

2021-01-13 11:47 UTC, valir commented
> @valir maybe i missed it but did you adress this comment already? [#740 (review)](https://github.com/Spotifyd/spotifyd/pull/740#pullrequestreview-566350806)

The link in there shows an overview of the diffs my branch brings-in. Looks like I don't get what should be done there.

2021-01-13 12:01 UTC, robinvd commented
oh yeah sorry about that it should have gone to a specific line, the function config.rs:SharedConfigValues:merge_with merges the config from disc and from the command line. If you could add the new field so that it is also merged

2021-01-13 15:05 UTC, robinvd approved these changes

2021-01-13 15:12 UTC, JojiiOfficial approved these changes

2021-01-13 15:13 UTC, merged